#!/usr/bin/env bash
# git auto squash
g:sq() {
	if [[ "$1" == "n" ]]; then
		eval "git rebase HEAD~$2 --interactive --autosquash -s recursive -X theirs"

	elif [[ "$1" == "h" ]]; then
		eval "git rebase $2 --interactive --autosquash -s recursive -X theris"

	else
		echo "specify the arguments"
		echo "sqash method params"
		echo "method-- n - by commits from head, h - by commit hash"
		echo "parameter numberber of comments | commit hash"
	fi
}

listening() {
    if [ $# -eq 0 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P
    elif [ $# -eq 1 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color $1
    else
        echo "Usage: listening [pattern]"
    fi
}

orelse() {
    ps xco pid=,command= | grep -i $1 | awk '{print $1}' | xargs kill -9
}

cman() {
    man $@
}

# # ex - archive extractor
# # usage: ex <file>
ex() {
	if [ -f $1 ]; then
		case $1 in
		*.tar.xz) tar xf $1 ;;
		*.tar.bz2) tar xjf $1 ;;
		*.tar.gz) tar xzf $1 ;;
		*.bz2) bunzip2 $1 ;;
		*.rar) unrar x $1 ;;
		*.gz) gunzip $1 ;;
		*.tar) tar xf $1 ;;
		*.tbz2) tar xjf $1 ;;
		*.tgz) tar xzf $1 ;;
		*.zip) unzip $1 ;;
		*.Z) uncompress $1 ;;
		*.7z) 7z x $1 ;;
		*) echo "'$1' cannot be extracted via ex()" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}
